
# General information:

# default image only for jobs without image set
image:  ${DOCKER_HOST_PATH}/alpine/git:v2.30.1

.shared_scm_runner_medium3:
  tags:
    - scm-eks-shared-medium3

variables:
  # Use Pre-Filled variables
  SPRINT_START_DATE:
    value: ""
    description: Please Enter Sprint Start Date in this format "2025-03-10T00:00:00Z"
  SPRINT_NAME:
    value: ""
    description: Enter name of Sprint in this format "SPRINT 3"
  FILE_NAME:
    value: ""
    description: Enter Correct file name in this format "PI6SP3-MR-stats-v1.xlsx"
  # General variables to execute pipeline
  TOKEN: $GITLAB_API_TOKEN
  PER_PAGE: "200"



fetch_mr-reviews:
  extends: [ .shared_scm_runner_medium3 ]
  image: DOCKER_HOST_PATH/customimages/scm/python-gitlab-alpine:3.11.9-4.4.0-3.18.6-2
  cache:
    key: "${CI_PROJECT_PATH_SLUG}"
    paths:
      - .cache/pip
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - pip install --upgrade pip
    - pip install requests
    - pip install openpyxl
    - python fetch_mr_reviews.py
  artifacts:
    paths:
      - "*.json"
      - "*.xlsx"
    expire_in: 1 week
